messageUtil = {
  success: "Success",
  resourceCreated: "Resource created",
  resourceUpdated: "Resource updated",
  resourceDeleted: "Resource deleted",
  resourceNotFound: "Resource not found",
  tokenInvalid: "Verification code is invalid",
  userRegister: "Register successful",
  loginSuccessful: "login successful",
  logoutSuccessful: "Logout successful",
  updateSuccess: "Updated successful",
  validationErrors: "Validation Errors",
  incorrectPassword: "Password is not correct",
  serverError: "Internal server error",
  emailAlreadyExist: "User already exist",
  notFound: "User not found",
  tokenRegistered: "User app token registered",
  found: "Users found successful",
  invalidCurrentPassword: "Current password is not correct",
  methodUnderDev: "method under development",
  resourceNotCreated: "Resource not created",
  invalidDate: "Invalid date formate",
  invalidDoctorId: "Please provide valid doctor id",
  invalidMedicalCenterId: "Please privide valid medical center id",
  selectDay: "Please select atleast one day",
  invalidStartDate: "Start date must be lesser or euqal to end date",
};

module.exports = { messageUtil };
